### ISSUE TITLE
2.0.1 undefined method `[]' for #<Set: {#<MIME::Type: application/json>}>

### ISSUE THREAD

**Issue by g3ortega** [nylas/nylas-ruby#81]
Hi, I'm having an issue when I try to send a draft, after updating from 2.0 to 2.0.1, using ruby 2.2.4

Here a test with the same snippet you provide. 

``` ruby
2.2.4 :018 > nylas.drafts.build({ :to => [{:name => 'Ben Gotow',
2.2.4 :019 >                                         :email => 'algo@algo.com'}],
2.2.4 :020 >                                     :subject => "Sent by Ruby",
2.2.4 :021 >                                     :body => "Hi there!<strong>This is HTML</strong>"}).send!
NoMethodError: undefined method `[]' for #<Set: {#<MIME::Type: application/json>}>
        from /Users/gerardo/.rvm/gems/ruby-2.2.4/gems/rest-client-1.6.7/lib/restclient/request.rb:307:in `type_for_extension'
        from /Users/gerardo/.rvm/gems/ruby-2.2.4/gems/rest-client-1.6.7/lib/restclient/request.rb:312:in `type_for_extension'
        from /Users/gerardo/.rvm/gems/ruby-2.2.4/gems/rest-client-1.6.7/lib/restclient/request.rb:278:in `block in stringify_headers'
        from /Users/gerardo/.rvm/gems/ruby-2.2.4/gems/rest-client-1.6.7/lib/restclient/request.rb:272:in `each'
        from /Users/gerardo/.rvm/gems/ruby-2.2.4/gems/rest-client-1.6.7/lib/restclient/request.rb:272:in `inject'
        from /Users/gerardo/.rvm/gems/ruby-2.2.4/gems/rest-client-1.6.7/lib/restclient/request.rb:272:in `stringify_headers'
        from /Users/gerardo/.rvm/gems/ruby-2.2.4/gems/rest-client-1.6.7/lib/restclient/request.rb:92:in `make_headers'
        from /Users/gerardo/.rvm/gems/ruby-2.2.4/gems/rest-client-1.6.7/lib/restclient/request.rb:58:in `initialize'
        from /Users/gerardo/.rvm/gems/ruby-2.2.4/gems/rest-client-1.6.7/lib/restclient/request.rb:33:in `new'
        from /Users/gerardo/.rvm/gems/ruby-2.2.4/gems/rest-client-1.6.7/lib/restclient/request.rb:33:in `execute'
        from /Users/gerardo/.rvm/gems/ruby-2.2.4/gems/rest-client-1.6.7/lib/restclient.rb:72:in `post'
        from /Users/gerardo/.rvm/gems/ruby-2.2.4/gems/nylas-2.0.1/lib/draft.rb:34:in `send!'
        from (irb):21
        from /Users/gerardo/.rvm/gems/ruby-2.2.4/gems/railties-4.2.6/lib/rails/commands/console.rb:110:in `start'
        from /Users/gerardo/.rvm/gems/ruby-2.2.4/gems/railties-4.2.6/lib/rails/commands/console.rb:9:in `start'
        from /Users/gerardo/.rvm/gems/ruby-2.2.4/gems/railties-4.2.6/lib/rails/commands/commands_tasks.rb:68:in `console'
... 7 levels...
        from /Users/gerardo/.rvm/gems/ruby-2.2.4/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:268:in `load'
        from /Users/gerardo/.rvm/gems/ruby-2.2.4/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:268:in `block in load'
        from /Users/gerardo/.rvm/gems/ruby-2.2.4/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:240:in `load_dependency'
        from /Users/gerardo/.rvm/gems/ruby-2.2.4/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:268:in `load'
        from /Users/gerardo/.rvm/gems/ruby-2.2.4/gems/spring-1.7.1/lib/spring/commands/rails.rb:6:in `call'
        from /Users/gerardo/.rvm/gems/ruby-2.2.4/gems/spring-1.7.1/lib/spring/command_wrapper.rb:38:in `call'
        from /Users/gerardo/.rvm/gems/ruby-2.2.4/gems/spring-1.7.1/lib/spring/application.rb:191:in `block in serve'
        from /Users/gerardo/.rvm/gems/ruby-2.2.4/gems/spring-1.7.1/lib/spring/application.rb:161:in `fork'
        from /Users/gerardo/.rvm/gems/ruby-2.2.4/gems/spring-1.7.1/lib/spring/application.rb:161:in `serve'
        from /Users/gerardo/.rvm/gems/ruby-2.2.4/gems/spring-1.7.1/lib/spring/application.rb:131:in `block in run'
        from /Users/gerardo/.rvm/gems/ruby-2.2.4/gems/spring-1.7.1/lib/spring/application.rb:125:in `loop'
        from /Users/gerardo/.rvm/gems/ruby-2.2.4/gems/spring-1.7.1/lib/spring/application.rb:125:in `run'
        from /Users/gerardo/.rvm/gems/ruby-2.2.4/gems/spring-1.7.1/lib/spring/application/boot.rb:19:in `<top (required)>'
        from /Users/gerardo/.rvm/rubies/ruby-2.2.4/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        from /Users/gerardo/.rvm/rubies/ruby-2.2.4/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        from -e:1:in `<main>'2.2.4 :022 > 
```

**Comment by dvallance** [comment]
I got by this issue by updating the rest-client gem to 1.8, and then having to downgrade mime-types to under version 3.

If you use bundler try. 
```
bundle update --source rest-client mime-types
```
